version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
    networks:
      - laranet
    container_name: "nginx_${PROJECT_NAME:?err}"

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
      - ./configs/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: 1000:1000
    networks:
      - laranet
    container_name: "php_${PROJECT_NAME:?err}"

  composer:
    image: composer:latest
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer", "--ignore-platform-reqs"]
    user: 1000:1000
    depends_on:
      - php
    networks:
      - laranet
    container_name: "composer_${PROJECT_NAME:?err}"

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    user: 1000:1000
    depends_on:
      - db
    networks:
      - laranet
    container_name: "artisan_${PROJECT_NAME:?err}"

  db:
    image: mariadb:10.9.2
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME:?err}"
      MYSQL_USER: "${DB_USER:?err}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?err}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:?err}"
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - laranet
    container_name: "db_${PROJECT_NAME:?err}"

  phpmyadmin:
    image: phpmyadmin:latest
    links: 
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    depends_on: 
      - db
    networks:
      - laranet
    container_name: "phpmyadmin_${PROJECT_NAME:?err}"

  phploy:
    build:
      context: ./dockerfiles
      dockerfile: phploy.dockerfile
    volumes: 
      - ./:/var/www/html
    working_dir: /var/www/html
    user: 1000:1000
    entrypoint: ["phploy"]
    networks:
      - laranet
    container_name: "phploy_${PROJECT_NAME:?err}"

  npm:
    image: node:18.8
    ports:
      - 3000:3000
      - 3001:3001
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laranet
    container_name: "npm_${PROJECT_NAME:?err}"

networks:
  laranet:
