version: "3.9"
services:
  laravel:
    image: "nginx:stable-alpine"
    ports:
        - "80:80"
    networks:
      - laravelnet

  mysql:
    image: "mariadb:10.9.2"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravelnet



networks:
  laravelnet:
